import { leaveRequestCreate, toIsoDate, type IsoDate } from '@widedrop/shared';
import type { App } from '../../app.js';
import { notFound } from '../../lib/errors.js';
import { requirePrincipal } from '../../plugins/authenticate.js';
import {
  assertEmployeeInScope,
  assertPermission,
  employeeScopeFor,
  employeeWhere,
} from '../../services/auth/authorization.js';
import {
  holidaysFor,
  resolveLeaveDays,
  submitLeaveRequest,
  withdrawLeaveRequest,
} from '../../services/leave/service.js';

/**
 * Leave.
 *
 * Read scope is whatever the principal's `leave:read` grant allows: an
 * employee sees their own, a manager their reporting chain, HR the
 * organisation. The filter is part of the query the database runs, so a
 * caller cannot widen it by passing an employee id.
 */
export async function leaveRoutes(app: App): Promise<void> {
  const db = app.db;
  const env = app.env;

  /* ---------------------------------------------------------------- */
  /* GET /leave — balances, types and the calendar in one call         */
  /* ---------------------------------------------------------------- */

  app.get('/api/v1/leave', { onRequest: app.authenticate() }, async (request) => {
    const principal = requirePrincipal(request);
    assertPermission(principal, 'leave:read', 'SELF');

    if (!principal.employeeId) {
      return { period: null, balances: [], types: [], holidays: [], upcoming: [] };
    }

    const today = toIsoDate(new Date());

    const period = await db.leavePeriod.findFirst({
      where: {
        organizationId: principal.organizationId,
        startDate: { lte: new Date(today) },
        endDate: { gte: new Date(today) },
      },
      select: { id: true, name: true, startDate: true, endDate: true, isClosed: true },
    });

    // No leave year open is a real state, not an error: it is what a new
    // organisation looks like before People Ops sets one up. The screen says
    // so rather than showing zeroes.
    if (!period) {
      return { period: null, balances: [], types: [], holidays: [], upcoming: [] };
    }

    const [balances, types, holidays, upcoming] = await Promise.all([
      db.leaveBalance.findMany({
        where: {
          organizationId: principal.organizationId,
          employeeId: principal.employeeId,
          leavePeriodId: period.id,
        },
        select: {
          id: true,
          openingDays: true,
          accruedDays: true,
          carriedForwardDays: true,
          consumedDays: true,
          reservedDays: true,
          lapsedDays: true,
          adjustedDays: true,
          availableDays: true,
          entitlementDays: true,
          leaveType: {
            select: { id: true, code: true, name: true, isPaid: true, displayOrder: true },
          },
        },
        orderBy: { leaveType: { displayOrder: 'asc' } },
      }),

      db.leaveType.findMany({
        where: { organizationId: principal.organizationId, isActive: true },
        orderBy: { displayOrder: 'asc' },
        select: {
          id: true,
          code: true,
          name: true,
          isPaid: true,
          allowsHalfDay: true,
          minNoticeDays: true,
          documentRequiredAfterDays: true,
          requiresApproval: true,
        },
      }),

      holidayList(db, principal.organizationId, principal.employeeId, today),

      db.leaveRequest.findMany({
        where: {
          organizationId: principal.organizationId,
          employeeId: principal.employeeId,
          status: { in: ['PENDING_APPROVAL', 'APPROVED'] },
          endDate: { gte: new Date(today) },
        },
        orderBy: { startDate: 'asc' },
        take: 10,
        select: {
          id: true,
          status: true,
          startDate: true,
          endDate: true,
          workingDays: true,
          leaveType: { select: { name: true, code: true } },
        },
      }),
    ]);

    return {
      period: {
        id: period.id,
        name: period.name,
        startDate: toIsoDate(period.startDate),
        endDate: toIsoDate(period.endDate),
        isClosed: period.isClosed,
      },

      // Every figure is a stored column. `availableDays` is generated by the
      // database from the others, so the bar and the number beside it cannot
      // disagree.
      balances: balances.map((balance) => ({
        id: balance.id,
        typeId: balance.leaveType.id,
        code: balance.leaveType.code,
        name: balance.leaveType.name,
        isPaid: balance.leaveType.isPaid,
        openingDays: Number(balance.openingDays),
        accruedDays: Number(balance.accruedDays),
        carriedForwardDays: Number(balance.carriedForwardDays),
        consumedDays: Number(balance.consumedDays),
        reservedDays: Number(balance.reservedDays),
        lapsedDays: Number(balance.lapsedDays),
        adjustedDays: Number(balance.adjustedDays),
        availableDays: Number(balance.availableDays),
        entitlementDays: Number(balance.entitlementDays),
      })),

      types,
      holidays,

      upcoming: upcoming.map((leave) => ({
        id: leave.id,
        status: leave.status,
        startDate: toIsoDate(leave.startDate),
        endDate: toIsoDate(leave.endDate),
        workingDays: Number(leave.workingDays),
        typeName: leave.leaveType.name,
        typeCode: leave.leaveType.code,
      })),
    };
  });

  /* ---------------------------------------------------------------- */
  /* GET /leave/requests                                               */
  /* ---------------------------------------------------------------- */

  app.get('/api/v1/leave/requests', { onRequest: app.authenticate() }, async (request) => {
    const principal = requirePrincipal(request);
    assertPermission(principal, 'leave:read', 'SELF');

    const { status, limit } = request.query as { status?: string; limit?: string };
    const scope = await employeeScopeFor(db, principal, 'leave:read');

    const requests = await db.leaveRequest.findMany({
      where: {
        organizationId: principal.organizationId,
        ...employeeWhere(scope),
        ...(status ? { status: status as never } : {}),
      },
      orderBy: { startDate: 'desc' },
      take: Math.min(Number(limit) || 50, 200),
      select: {
        id: true,
        status: true,
        startDate: true,
        endDate: true,
        startPortion: true,
        endPortion: true,
        workingDays: true,
        reason: true,
        decisionNote: true,
        submittedAt: true,
        decidedAt: true,
        leaveType: { select: { id: true, name: true, code: true, isPaid: true } },
        employee: { select: { id: true, fullName: true, initials: true } },
      },
    });

    return {
      items: requests.map((leave) => ({
        id: leave.id,
        status: leave.status,
        startDate: toIsoDate(leave.startDate),
        endDate: toIsoDate(leave.endDate),
        startPortion: leave.startPortion,
        endPortion: leave.endPortion,
        workingDays: Number(leave.workingDays),
        reason: leave.reason,
        decisionNote: leave.decisionNote,
        submittedAt: leave.submittedAt?.toISOString() ?? null,
        decidedAt: leave.decidedAt?.toISOString() ?? null,
        type: leave.leaveType,
        employee: leave.employee,
        // Only a request of your own can be withdrawn from here.
        canWithdraw:
          leave.employee.id === principal.employeeId &&
          ['PENDING_APPROVAL', 'APPROVED'].includes(leave.status),
      })),
    };
  });

  /* ---------------------------------------------------------------- */
  /* POST /leave/preview — what a request would cost, before sending   */
  /* ---------------------------------------------------------------- */

  app.post('/api/v1/leave/preview', { onRequest: app.authenticate() }, async (request) => {
    const principal = requirePrincipal(request);
    assertPermission(principal, 'leave:request', 'SELF');

    const body = leaveRequestCreate.parse(request.body);
    if (!principal.employeeId) return { workingDays: 0, days: [] };

    // The same calculation the submission will do, run by the same code. The
    // preview cannot promise a count the submission then contradicts.
    const { dates, weekOffDays } = await holidaysFor(db, {
      organizationId: principal.organizationId,
      employeeId: principal.employeeId,
      from: body.startDate,
      to: body.endDate,
    });

    const days = resolveLeaveDays({
      startDate: body.startDate,
      endDate: body.endDate,
      startPortion: body.startPortion,
      endPortion: body.endPortion,
      holidays: dates,
      weekOffDays,
    });

    return {
      workingDays: days.reduce((total, day) => total + day.fraction, 0),
      days: days.map((day) => ({ date: day.date, portion: day.portion })),
      excluded: {
        holidays: [...dates].filter((date) => date >= body.startDate && date <= body.endDate),
      },
    };
  });

  /* ---------------------------------------------------------------- */
  /* POST /leave/requests                                              */
  /* ---------------------------------------------------------------- */

  app.post(
    '/api/v1/leave/requests',
    { onRequest: app.authenticate(), config: { rateLimitName: 'write' } },
    async (request, reply) => {
      const principal = requirePrincipal(request);
      assertPermission(principal, 'leave:request', 'SELF');

      const body = leaveRequestCreate.parse(request.body);

      const created = await db.$transaction((tx) =>
        submitLeaveRequest(
          tx,
          principal,
          {
            leaveTypeId: body.leaveTypeId,
            startDate: body.startDate,
            endDate: body.endDate,
            startPortion: body.startPortion,
            endPortion: body.endPortion,
            reason: body.reason ?? null,
          },
          env.AUDIT_HMAC_KEY,
        ),
      );

      return reply.status(201).send(created);
    },
  );

  /* ---------------------------------------------------------------- */
  /* POST /leave/requests/:id/withdraw                                 */
  /* ---------------------------------------------------------------- */

  app.post<{ Params: { id: string } }>(
    '/api/v1/leave/requests/:id/withdraw',
    { onRequest: app.authenticate(), config: { rateLimitName: 'write' } },
    async (request, reply) => {
      const principal = requirePrincipal(request);
      assertPermission(principal, 'leave:withdraw', 'SELF');

      await db.$transaction((tx) =>
        withdrawLeaveRequest(tx, principal, { requestId: request.params.id }, env.AUDIT_HMAC_KEY),
      );

      return reply.status(204).send();
    },
  );

  /* ---------------------------------------------------------------- */
  /* GET /leave/balances/:employeeId — a manager or HR looking at      */
  /* someone else's                                                    */
  /* ---------------------------------------------------------------- */

  app.get<{ Params: { employeeId: string } }>(
    '/api/v1/leave/balances/:employeeId',
    { onRequest: app.authenticate() },
    async (request) => {
      const principal = requirePrincipal(request);
      assertPermission(principal, 'leave:read', 'SELF');

      // Scope is checked against this employee, not against a role name.
      await assertEmployeeInScope(db, principal, 'leave:read', request.params.employeeId);

      const today = toIsoDate(new Date());
      const period = await db.leavePeriod.findFirst({
        where: {
          organizationId: principal.organizationId,
          startDate: { lte: new Date(today) },
          endDate: { gte: new Date(today) },
        },
        select: { id: true, name: true },
      });
      if (!period) return { period: null, balances: [] };

      const balances = await db.leaveBalance.findMany({
        where: {
          organizationId: principal.organizationId,
          employeeId: request.params.employeeId,
          leavePeriodId: period.id,
        },
        orderBy: { leaveType: { displayOrder: 'asc' } },
        select: {
          availableDays: true,
          entitlementDays: true,
          consumedDays: true,
          reservedDays: true,
          leaveType: { select: { code: true, name: true } },
        },
      });

      return {
        period,
        balances: balances.map((balance) => ({
          code: balance.leaveType.code,
          name: balance.leaveType.name,
          availableDays: Number(balance.availableDays),
          entitlementDays: Number(balance.entitlementDays),
          consumedDays: Number(balance.consumedDays),
          reservedDays: Number(balance.reservedDays),
        })),
      };
    },
  );

  /* ---------------------------------------------------------------- */
  /* GET /leave/requests/:id                                           */
  /* ---------------------------------------------------------------- */

  app.get<{ Params: { id: string } }>(
    '/api/v1/leave/requests/:id',
    { onRequest: app.authenticate() },
    async (request) => {
      const principal = requirePrincipal(request);
      assertPermission(principal, 'leave:read', 'SELF');

      const scope = await employeeScopeFor(db, principal, 'leave:read');

      const leave = await db.leaveRequest.findFirst({
        where: {
          id: request.params.id,
          organizationId: principal.organizationId,
          ...employeeWhere(scope),
        },
        select: {
          id: true,
          status: true,
          startDate: true,
          endDate: true,
          startPortion: true,
          endPortion: true,
          workingDays: true,
          reason: true,
          decisionNote: true,
          submittedAt: true,
          decidedAt: true,
          leaveType: { select: { id: true, name: true, code: true, isPaid: true } },
          employee: { select: { id: true, fullName: true, initials: true } },
          days: { orderBy: { date: 'asc' }, select: { date: true, portion: true } },
        },
      });

      if (!leave) throw notFound('That leave request');

      return {
        ...leave,
        startDate: toIsoDate(leave.startDate),
        endDate: toIsoDate(leave.endDate),
        workingDays: Number(leave.workingDays),
        submittedAt: leave.submittedAt?.toISOString() ?? null,
        decidedAt: leave.decidedAt?.toISOString() ?? null,
        days: leave.days.map((day) => ({ date: toIsoDate(day.date), portion: day.portion })),
      };
    },
  );
}

/** The holidays ahead for one employee's location. */
async function holidayList(
  db: App['db'],
  organizationId: string,
  employeeId: string,
  from: IsoDate,
) {
  const employment = await db.employeeEmployment.findFirst({
    where: { employeeId, effectiveTo: null },
    select: { location: { select: { holidayCalendarId: true } } },
  });

  const calendarId = employment?.location.holidayCalendarId;
  if (!calendarId) return [];

  const holidays = await db.holiday.findMany({
    where: { organizationId, holidayCalendarId: calendarId, date: { gte: new Date(from) } },
    orderBy: { date: 'asc' },
    take: 24,
    select: { id: true, name: true, date: true, kind: true },
  });

  return holidays.map((holiday) => ({
    id: holiday.id,
    name: holiday.name,
    date: toIsoDate(holiday.date),
    kind: holiday.kind,
  }));
}
